// This file is automatically generated. Do not edit it directly.

// Your Opix credentials
export const CLIENT_ID = "558446b413c6f9e6e77fe62c459d8af3";

// Import your Opix SDK factory
import { createClient } from "./sdk";

// Import the Opix client like this:
// import { opix } from "@/integrations/opix/client";

export const opix = createClient(CLIENT_ID, API_KEY);
